{
 "title": "dash-forum-api",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{application=\"$application\", instance=\"$instance\"},pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "HEAP USED",
     "type": "gauge",
     "description": "Mémoria heap utilizada",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"heap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU UTILIZATION",
     "type": "timeseries",
     "description": "Utilização de CPU",
     "gridPos": { "h": 9, "w": 10, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "System CPU usage"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "Process CPU usage"
      }
     ]
    },
    {
     "title": "NON-HEAP USED",
     "type": "gauge",
     "description": "Memória non-heap utilizada",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"}) * 100 / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", area=\"nonheap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LOAD AVERAGE",
     "type": "timeseries",
     "description": "Média de uso de CPU",
     "gridPos": { "h": 9, "w": 10, "x": 5, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "Load average [1m]"
      },
      {
       "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "CPU core size"
      }
     ]
    }
   ]
  },
  {
   "title": "API Basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPTIME",
     "type": "stat",
     "description": "API uptime",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "USERS LOGGED",
     "type": "stat",
     "description": "Usuários logados no último minuto.",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_success_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JDBC POOL",
     "type": "stat",
     "description": "Pool de conexões JDBC",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CONNECTION STATE",
     "type": "timeseries",
     "description": "Estado das conexões com o database.",
     "gridPos": { "h": 8, "w": 8, "x": 11, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "hikaricp_connections_idle{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "START TIME",
     "type": "stat",
     "description": "Hora da inicialização da API",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AUTH ERRORS",
     "type": "stat",
     "description": "Erros de autenticação no último minuto.",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_error_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB CONNECTION TIMEOUT",
     "type": "stat",
     "description": "Conexões com o database em timeout",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", pool=\"$pool\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WARN & ERROR LOG",
     "type": "timeseries",
     "description": "Warning e erros logados nos últimos 5 minutos.",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"warn\"}[5m]))",
       "legendFormat": "warn"
      },
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", level=\"error\"}[5m]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "API RED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL REQUESTS",
     "type": "stat",
     "description": "Número de requisições no último minuto",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ERROR 500",
     "type": "stat",
     "description": "Número de erros 500 no último minuto",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LATANCY AVERAGE",
     "type": "timeseries",
     "description": "Latência média do minuto",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(.90, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(.50, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "25%"
      }
     ]
    },
    {
     "title": "ERROR RATE",
     "type": "timeseries",
     "description": "Taxa de erro nos últimos 5 minutos",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "500"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "400"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "404"
      }
     ]
    },
    {
     "title": "RESPONSE TIME",
     "type": "timeseries",
     "description": "Tempo de resposta no último minuto",
     "gridPos": { "h": 5, "w": 12, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "REQUEST COUNT",
     "type": "timeseries",
     "description": "Número de requisições por endpoint no último minuto",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos\"}[1m]))",
       "legendFormat": "/topicos"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/topicos/{id}\"}[1m]))",
       "legendFormat": "/topicos/{id}"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", uri=\"/auth\"}[1m]))",
       "legendFormat": "/auth"
      }
     ]
    },
    {
     "title": "AVERAGE REQUEST DURATION",
     "type": "timeseries",
     "description": "Duração média de requisições no último minuto",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri=\"/auth\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "MAX REQUEST DURATION",
     "type": "timeseries",
     "description": "Duração máxima de uma requisição",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", job=\"app-forum-api\", status=\"200\", uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    }
   ]
  }
 ]
}